import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {
      type: 'link',
      label: 'V0.1', // The link label
      href: 'http://docs.monoz.io/v1', // The external URL
    },
  ],

  // But you can create a sidebar manually
 
  // tutorialSidebar: [
  //   'Quickstart/index',
  //   'Quickstart/monoZJet',
  //   'datasheets/index',
  //   'datasheets/monoZJet',
  //   'datasheets/monoZero1WG',
  //   'faq',
  //   'intro',
  //   'monoZJet/datasheet',
  //   'monoZJet/hostcommunicationcommands',
  //   'monoZJet/hwintegrationguide',
  //   'monoZJet/index',
  //   'monoZJet/introduction',
  //   {
  //     type: 'link',
  //     label: 'External Link',
  //     href: 'https://www.example.com',
  //   },
  // ],
  
};

export default sidebars;
